name: "Deploy"
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v2.3.3

      # Install .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: "3.1.x"

      # Run tests
      # - name: Test
      # run: dotnet test

      # Generate the website
      # - name: Build
      # run: dotnet build --configuration Release

      # Generate content
      - name: Generator
        run: dotnet run --project Manager --configuration Release

      # Publish the website
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./fake-api/wwwroot
          # cname: demo.meziantou.net
